Repository googleapis/java-artifact-registry, pull requests merged in 2021-04, with the labels that each got.

#24 samples(deps): fix artifactIds and versions
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: api: artifactregistry, cla: yes, samples

#27 build(java): skip javadoc tests during dependencies test
  .github/sync-repo-settings.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#30 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#33 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#34 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: artifactregistry, automerge, cla: yes
