Repository googleapis/java-artifact-registry, pull requests merged in 2021-05, with the labels that each got.

#41 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: none

#42 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: artifactregistry, automerge, cla: yes

#44 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#48 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#49 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#51 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: artifactregistry, automerge, cla: yes, context: full

#53 chore: add cicd (devplat) team to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: artifactregistry, cla: yes

#54 chore: Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: api: artifactregistry, cla: yes, context: none

#60 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: artifactregistry, automerge, cla: yes

#56 chore: add cicd team with push access
  .github/sync-repo-settings.yaml
Labels: api: artifactregistry, cla: yes
