Repository googleapis/java-artifact-registry, pull requests merged in 2022-01, with the labels that each got.

#203 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: artifactregistry, owlbot:ignore

#208 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: artifactregistry, owlbot:ignore

#210 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: automerge, api: artifactregistry

#212 chore: add codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: artifactregistry
